routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('threads','ThreadsController@index');
Route::get('/threads/create','ThreadsController@create');
Route::get('threads/{channel}','ThreadsController@index');
Route::get('/threads/{channel}/{thread}','ThreadsController@show');
Route::patch('/threads/{channel}/{thread}','ThreadsController@update');
Route::delete('/threads/{channel}/{thread}','ThreadsController@destroy');
Route::post('/threads','ThreadsController@store');

/*for using in Replies.vue@fetch()*/
Route::get('/threads/{channel}/{thread}/replies','RepliesController@index');

Route::post('/threads/{channel}/{thread}/replies','RepliesController@store');
Route::patch('/replies/{reply}','RepliesController@update');
Route::delete('/replies/{reply}','RepliesController@destroy');

Route::post('/threads/{channel}/{thread}/subscriptions', 'ThreadSubscriptionsController@store')->middleware('auth');
Route::delete('/threads/{channel}/{thread}/subscriptions', 'ThreadSubscriptionsController@destroy')->middleware('auth');

Route::post('/replies/{reply}/favorites','FavoriteController@store');
Route::delete('/replies/{reply}/favorites','FavoriteController@destroy');

Route::get('profiles/{user}', 'ProfilesController@show')->name('profile');

Route::get('profiles/{user}/notifications', 'UserNotificationsController@index');
Route::delete('profiles/{user}/notifications/{notification}', 'UserNotificationsController@destroy');

// For autocomplete in NewReply.vue
Route::get('api/users', 'Api\UsersController@index');
Route::post('api/users/{user}/avatar', 'Api\UserAvatarController@store')->middleware('auth')->name('avatar');

app/Thread.php
<?php

namespace App;

use App\Events\ThreadReceivedNewReply;
use Illuminate\Database\Eloquent\Model;
use Stevebauman\Purify\Facades\Purify;


class Thread extends Model
{
    use RecordsActivity;

    protected $guarded = [];
    protected $with = ['creator', 'channel'];

    // For adding getIsSubscribedToAttributes to output array
    protected $appends = ['isSubscribedTo'];

    /*******eager load example*******/
    /**
     * protected static function boot()
     * {
     * parent::boot();
     *
     * static::addGlobalScope('replyCount', function ($builder){
     * $builder->withCount('replies');
     * });
     * }*/

    public function path()
    {
        return "/threads/{$this->channel->slug}/{$this->id}";
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function channel()
    {
        return $this->belongsTo(Channel::class);
    }

    /**
     * @param array $reply
     * @return Model
     */
    public function addReply($reply)
    {
        $reply = $this->replies()->create($reply);

        /*Send Notifications for subscriptions*/
        /*Send Notifications for username who mentioned in reply - when RepliesController@store is called*/

        event(new ThreadReceivedNewReply($reply));


        return $reply;
    }

    // For filtering
    public function scopeFilter($query, $filters)
    {
        return $filters->apply($query);
    }

    /**
     * @param int null $userId
     * @return $this
     */
    public function subscribe($userId = null)
    {
        $this->subscriptions()->create([
            'user_id' => $userId ?: auth()->id()
        ]);

        return $this;
    }

    public function unsubscribe($userId = null)
    {
        $this->subscriptions()
            ->where('user_id', $userId ?: auth()->id())
            ->delete();
    }

    public function subscriptions()
    {
        return $this->hasMany(ThreadSubscription::class);
    }

    public function getIsSubscribedToAttribute()
    {
        return $this->subscriptions()
            ->where('user_id', auth()->id())
            ->exists();
    }

    public function hasUpdatedFor($user = null)
    {
        $user = $user ?: auth()->user();
        // Look in the cache for the proper key.
        // Compare that carbon instance with the $thread->updated_at
        $key = $user->visitedThreadCacheKey($this);

        // returns $this->updated_at if is > than $key = it means unread
        return $this->updated_at > cache($key);
    }

    public function visits()
    {
        return new Visits($this);
    }

    public function getBodyAttribute($body)
    {
        return Purify::clean($body);
    }
}

app/Http/Controllers/ThreadsController.php
<?php

namespace App\Http\Controllers;

use App\Channel;
use App\Filters\ThreadFilters;
use App\Thread;
use App\Trending;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Validation\ValidationException;

class ThreadsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }

    /**
     * Display a listing of the resource.
     *
     * @param Channel $channel
     * @param ThreadFilters $filters
     * @param Trending $trending
     * @return Response
     */
    public function index(Channel $channel, ThreadFilters $filters, Trending $trending)
    {
        $threads = $this->getThreads($channel, $filters);

        if (request()->wantsJson()) {
            return $threads;
        }

        return view('threads.index', [
            'threads' => $threads,
            'trending' => $trending->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('threads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     * @throws ValidationException
     */
    public function store()
    {
        $this->validateThread();

        $thread = Thread::create([
            'user_id' => auth()->id(),
            'channel_id' => request('channel_id'),
            'title' => request('title'),
            'body' => request('body')
        ]);

        return redirect($thread->path())
            ->with('flash', 'Your thread has been published!');
    }

    /**
     * Display the specified resource.
     *
     * @param $channel
     * @param Thread $thread
     * @param Trending $trending
     * @return Response
     */
    public function show($channel, Thread $thread, Trending $trending)
    {
        // Record that the user visited this page.
        // Record a timestamp
        if (auth()->check()) {
            auth()->user()->read($thread);
        }

        // trends_count++
        $trending->push($thread);
        // visit_count++
        $thread->visits()->record();

        return view('threads.show', compact('thread'));
    }

    public function update($channel, Thread $thread)
    {
        $this->authorize('update', $thread);
        $thread->update(request()->validate(
            [
                'title' => 'required',
                'body' => 'required',
//                'channel' => 'required'
            ]
        ));
        return $thread;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $channel
     * @param Thread $thread
     * @return Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy($channel, Thread $thread)
    {
        $this->authorize('update', $thread);

        // When a reply is deleting, it's activity must be deleted too
        // each loop for deleting all replies that belongs to this thread
        $thread->replies->each->delete();

        $thread->delete();

        if (request()->wantsJson()) {
            return response([], 204);
        }
        return redirect('/threads');
    }

    /**
     * @param Channel $channel
     * @param ThreadFilters $filters
     * @return mixed
     */
    protected function getThreads(Channel $channel, ThreadFilters $filters)
    {
        $threads = Thread::filter($filters);
        /*(new Thread)->filter($filters)*/

        if ($channel->exists) {
            $threads = Thread::where('channel_id', $channel->id);
        }

        return $threads->paginate();
    }

    protected function validateThread()
    {
        request()->validate([
            'channel_id' => 'required | exists:channels,id',
            'title' => 'required | spamfree',
            'body' => 'required | spamfree'
        ]);
    }

}

resources/views/threads/_list.blade.php
@forelse($threads as $thread)
    <div class="card form-group">
        <div class="card-header">
            <div class="level">

                <div class="flex">
                    <h4>
                        <a href="{{ $thread->path() }}">
                            @if(auth()->check() && $thread->hasUpdatedFor(auth()->user()))
                                <strong>{{ $thread->title }}</strong>
                            @else
                                {{ $thread->title }}
                            @endif
                        </a>
                    </h4>

                    <h5>Posted by: <a href="{{ route('profile', $thread->creator) }}">{{ $thread->creator->name }}</a></h5>
                </div>

                <a href="{{ $thread->path() }}">{{ $thread->replies_count }}
                    {{ \Illuminate\Support\Str::plural('comment', $thread->replies_count) }}
                </a>
            </div>

        </div>

        <div class="card-body">
            <div class="body">{!! $thread->body !!}</div>
        </div>
        <div class="card-footer">
            {{ $thread->visits()->count() }} <i class="fa fa-eye"></i>
        </div>
    </div>
@empty
    <h3>There are no records</h3>
@endforelse

resources/views/threads/_thread_card.blade.php
{{--Editing thread--}}
<div class="card" v-if="editing">
    <div class="card-header">

        <div class="level">
            <input type="text" class="form-control" v-model="form.title">
        </div>

    </div>

    <div class="card-body">
        <wysiwyg name="body" v-model="form.body"></wysiwyg>
    </div>

    <div class="card-footer">
        <div class="level">
            <button class="btn btn-primary btn-sm level-item" @click="update">Update</button>
            <button class="btn btn-secondary btn-sm level-item" @click="resetForm">Cancel</button>
            @can('update', $thread)
                <form method="POST" action="{{ $thread->path() }}" class="ml-auto">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger btn-sm">Delete Thread</button>
                </form>
            @endcan
        </div>
    </div>
</div>

{{--Viewing thread--}}
<div class="card" v-else>
    <div class="card-header">

        <div class="level">
            <img src="{{ $thread->creator->avatar_path }}" alt="avatar" width="40" class="mr-1 rounded-circle">

            <span class="flex">
                <a href="{{ url('profiles/'. $thread->creator->name) }}">
                    {{ $thread->creator->name }}
                </a> posted: <span v-text="title"></span>
            </span>

        </div>

    </div>

    <div class="card-body">
        <div class="body" v-html="body"></div>
    </div>

    <div class="card-footer" v-if="authorize('owns', thread)">
        <button class="btn btn-secondary btn-sm" @click="editing = true">Edit</button>
    </div>
</div>

resources/views/threads/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Create a New Thread</div>

                    <div class="card-body">
                        <form action="/threads" method="POST">
                            @csrf

                            <div class="form-group">
                                <div class="form-group">
                                    <label for="channel_id">Choose a Channel:</label>
                                    <select name="channel_id" id="channel_id" class="form-control" required>
                                        <option value="">Choose One...</option>
                                        @foreach($channels as $channel)
                                            <option value="{{ $channel->id }}"
                                                    {{ old('channel_id') == $channel->id ? 'selected' : '' }}>
                                                {{ $channel->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="title">Title:</label>
                                <input type="text" class="form-control" id="title" name="title"
                                       value="{{ old('title') }}" required>
                            </div>
                            <div class="form-group">
                                <label for="body">Body:</label>
                                <wysiwyg name="body"></wysiwyg>
                            </div>
                            <button type="submit" class="btn btn-secondary">Publish</button>
                        </form>
                        <br>
                        @if(count($errors))
                            <ul class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/threads/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">

            <div class="col-md-8">
                @include('threads._list')
                {{ $threads->links() }}
            </div>

            <div class="col-md-4">
                @if(count($trending))
                    <div class="card form-group">

                        <div class="card-header">
                            Trending Threads
                        </div>
                        <div class="card-body">
                            <ul class="list-group">
                                @foreach($trending as $trend)
                                    <li class="list-group-item"><a
                                                href="{{ url($trend->path) }}">{{str_limit($trend->title, 35)}}</a></li>
                                @endforeach
                            </ul>
                        </div>

                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/threads/show.blade.php
@extends('layouts.app')
@section('styles')
    <link href="{{ asset('css/jquery.atwho.css') }}" rel="stylesheet">
@endsection

@section('content')
    <thread-view :thread="{{ $thread }}" inline-template>
        <div class="container" v-cloak>
            <div class="row">
                <div class="col-md-8">

                    @include('threads._thread_card')

                    <replies @added="repliesCount++"  {{--this.$emit('added');--}}
                             @removed="repliesCount--">
                    </replies>

                    <br>
                </div>

                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <p>
                                This thread was published {{ $thread->created_at->diffForHumans() }} by
                                <a href="#">{{ $thread->creator->name }}</a>, and currently has
                                <span v-text="repliesCount"></span>
                                {{ \Illuminate\Support\Str::plural('comment', $thread->replies_count) }}.
                            </p>

                            <p>
                                {{--json_encode is for bool output--}}
                                <subscribe-button :active="{{ json_encode($thread->isSubscribedTo) }}"></subscribe-button>
                            </p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </thread-view>
@endsection